shop_enabled: false

announcement_enabled: false
contact_form_enabled: true
announcement_message: "The shop will be closed this Wednesday"

title: Heart of Handmade
description: Unique gift shop in Barnsley town centre offering homemade crafts, art and workshops
url: https://heartofhandmade.co.uk
keywords: art,crafts,workshops,gift,gifts,crafting,barnsley,yorkshire,shop,gallery,handmade

exclude:
  - README.txt
  - LICENSE.txt
